const constants = {
  DEFAULT_WIDTH: 40,
  DEFAULT_HEIGHT: 30,
  CELL_SIZE: 10,
  MIN_VALUE_SPEED_SLIDER: 1,
  MAX_VALUE_SPEED_SLIDER: 5,
  CURRENT_VALUE_SPEED_SLIDER: 3,
  DEFAULT_DELAY: 600,
  MAX_DELAY: 1000,
  STEP_DELAY: 200,
  MINIMUM_ALIVE_NEIGHBORS: 2,
  MAXIMUM_ALIVE_NEIGHBORS: 3,
  ZEROED: 0,
  ASSIGNED: 1,
};

export default constants;
